# lab01
#
# This Makefile is provided to help you organize the files
# for submission. It comes with ABSOLUTELY NO WARRANY and you
# are ultimately responsible for the files you submit.

.PHONY: all clean
all: summorial.sml 
	zip lab01-handin.zip $^

clean:
	rm -f lab01-handin.zip
	rm -Rf .cm

