# hw01
#
# This Makefile is provided to help you organize the files
# for submission. It comes with ABSOLUTELY NO WARRANY and you
# are ultimately responsible for the files you submit.

.PHONY: all clean
all: errors.sml hosoya.sml 
	zip hw01-handin.zip $^

clean:
	rm -f hw01-handin.zip
	rm -Rf .cm

