# hw05
#
# This Makefile is provided to help you organize the files
# for submission. It comes with ABSOLUTELY NO WARRANY and you
# are ultimately responsible for the files you submit.

.PHONY: all clean
all: delimiters.sml subseq.sml 
	zip hw05-handin.zip $^

clean:
	rm -f hw05-handin.zip
	rm -Rf .cm

