# hw03
#
# This Makefile is provided to help you organize the files
# for submission. It comes with ABSOLUTELY NO WARRANY and you
# are ultimately responsible for the files you submit.

.PHONY: all clean
all: conway.sml factorization.sml listmult.sml treemin.sml 
	zip hw03-handin.zip $^

clean:
	rm -f hw03-handin.zip
	rm -Rf .cm

