# hw02
#
# This Makefile is provided to help you organize the files
# for submission. It comes with ABSOLUTELY NO WARRANY and you
# are ultimately responsible for the files you submit.

.PHONY: all clean
all: itree.sml robot.sml 
	zip hw02-handin.zip $^

clean:
	rm -f hw02-handin.zip
	rm -Rf .cm

