# hw04
#
# This Makefile is provided to help you organize the files
# for submission. It comes with ABSOLUTELY NO WARRANY and you
# are ultimately responsible for the files you submit.

.PHONY: all clean
all: balanced.sml isort.sml 
	zip hw04-handin.zip $^

clean:
	rm -f hw04-handin.zip
	rm -Rf .cm

